# https://rock-it.pl/how-to-write-excellent-dockerfiles/
# 1. Write .dockerignore
# 2. Container should do one thing
# 3. Merge multiple RUN commands into one
# 4. Remove unneeded files after each RUN step
# 5. Use proper base image
# 6. Set WORKDIR and CMD
# 7. Use ENTRYPOINT (optional)
# 8. Use "exec" inside entrypoint script
# 9. Prefer COPY over ADD
# 10. Optimize COPY and RUN
# 11. Specify default environment variables, ports and volumes

FROM alpine:latests
MAINTAINER hfar@tv2.dk

